#include <mpi.h>

// This file captures all of the predefined handles
// so that they can be referenced by dlsym, since
// this is not necessarily possible.
//
// MPICH, for example, defines predefined handles in
// the preprocessor, which means there are no symbols
// in the MPICH shared library.

// error codes
int IMPL_SUCCESS = MPI_SUCCESS;
int IMPL_ERR_BUFFER = MPI_ERR_BUFFER;
int IMPL_ERR_COUNT = MPI_ERR_COUNT;
int IMPL_ERR_TYPE = MPI_ERR_TYPE;
int IMPL_ERR_TAG = MPI_ERR_TAG;
int IMPL_ERR_COMM = MPI_ERR_COMM;
int IMPL_ERR_RANK = MPI_ERR_RANK;
int IMPL_ERR_REQUEST = MPI_ERR_REQUEST;
int IMPL_ERR_ROOT = MPI_ERR_ROOT;
int IMPL_ERR_GROUP = MPI_ERR_GROUP;
int IMPL_ERR_OP = MPI_ERR_OP;
int IMPL_ERR_TOPOLOGY = MPI_ERR_TOPOLOGY;
int IMPL_ERR_DIMS = MPI_ERR_DIMS;
int IMPL_ERR_ARG = MPI_ERR_ARG;
int IMPL_ERR_UNKNOWN = MPI_ERR_UNKNOWN;
int IMPL_ERR_TRUNCATE = MPI_ERR_TRUNCATE;
int IMPL_ERR_OTHER = MPI_ERR_OTHER;
int IMPL_ERR_INTERN = MPI_ERR_INTERN;
int IMPL_ERR_PENDING = MPI_ERR_PENDING;
int IMPL_ERR_IN_STATUS = MPI_ERR_IN_STATUS;
int IMPL_ERR_ACCESS = MPI_ERR_ACCESS;
int IMPL_ERR_AMODE = MPI_ERR_AMODE;
int IMPL_ERR_ASSERT = MPI_ERR_ASSERT;
int IMPL_ERR_BAD_FILE = MPI_ERR_BAD_FILE;
int IMPL_ERR_BASE = MPI_ERR_BASE;
int IMPL_ERR_CONVERSION = MPI_ERR_CONVERSION;
int IMPL_ERR_DISP = MPI_ERR_DISP;
int IMPL_ERR_DUP_DATAREP = MPI_ERR_DUP_DATAREP;
int IMPL_ERR_FILE_EXISTS = MPI_ERR_FILE_EXISTS;
int IMPL_ERR_FILE_IN_USE = MPI_ERR_FILE_IN_USE;
int IMPL_ERR_FILE = MPI_ERR_FILE;
int IMPL_ERR_INFO_KEY = MPI_ERR_INFO_KEY;
int IMPL_ERR_INFO_NOKEY = MPI_ERR_INFO_NOKEY;
int IMPL_ERR_INFO_VALUE = MPI_ERR_INFO_VALUE;
int IMPL_ERR_INFO = MPI_ERR_INFO;
int IMPL_ERR_IO = MPI_ERR_IO;
int IMPL_ERR_KEYVAL = MPI_ERR_KEYVAL;
int IMPL_ERR_LOCKTYPE = MPI_ERR_LOCKTYPE;
int IMPL_ERR_NAME = MPI_ERR_NAME;
int IMPL_ERR_NO_MEM = MPI_ERR_NO_MEM;
int IMPL_ERR_NOT_SAME = MPI_ERR_NOT_SAME;
int IMPL_ERR_NO_SPACE = MPI_ERR_NO_SPACE;
int IMPL_ERR_NO_SUCH_FILE = MPI_ERR_NO_SUCH_FILE;
int IMPL_ERR_PORT = MPI_ERR_PORT;
#if MPI_VERSION >= 4
int IMPL_ERR_PROC_ABORTED = MPI_ERR_PROC_ABORTED;
#endif
int IMPL_ERR_QUOTA = MPI_ERR_QUOTA;
int IMPL_ERR_READ_ONLY = MPI_ERR_READ_ONLY;
int IMPL_ERR_RMA_ATTACH = MPI_ERR_RMA_ATTACH;
int IMPL_ERR_RMA_CONFLICT = MPI_ERR_RMA_CONFLICT;
int IMPL_ERR_RMA_RANGE = MPI_ERR_RMA_RANGE;
int IMPL_ERR_RMA_SHARED = MPI_ERR_RMA_SHARED;
int IMPL_ERR_RMA_SYNC = MPI_ERR_RMA_SYNC;
int IMPL_ERR_RMA_FLAVOR = MPI_ERR_RMA_FLAVOR;
int IMPL_ERR_SERVICE = MPI_ERR_SERVICE;
#if MPI_VERSION >= 4
int IMPL_ERR_SESSION = MPI_ERR_SESSION;
#endif
int IMPL_ERR_SIZE = MPI_ERR_SIZE;
int IMPL_ERR_SPAWN = MPI_ERR_SPAWN;
int IMPL_ERR_UNSUPPORTED_DATAREP = MPI_ERR_UNSUPPORTED_DATAREP;
int IMPL_ERR_UNSUPPORTED_OPERATION = MPI_ERR_UNSUPPORTED_OPERATION;
#if MPI_VERSION >= 4
int IMPL_ERR_VALUE_TOO_LARGE = MPI_ERR_VALUE_TOO_LARGE;
#endif
int IMPL_ERR_WIN = MPI_ERR_WIN;
int IMPL_T_ERR_CANNOT_INIT = MPI_T_ERR_CANNOT_INIT;
#if 0
int IMPL_T_ERR_NOT_ACCESSIBLE = MPI_T_ERR_NOT_ACCESSIBLE;
#endif
int IMPL_T_ERR_NOT_INITIALIZED = MPI_T_ERR_NOT_INITIALIZED;
#if MPI_VERSION >= 4
int IMPL_T_ERR_NOT_SUPPORTED = MPI_T_ERR_NOT_SUPPORTED;
#endif
int IMPL_T_ERR_MEMORY = MPI_T_ERR_MEMORY;
int IMPL_T_ERR_INVALID = MPI_T_ERR_INVALID;
int IMPL_T_ERR_INVALID_INDEX = MPI_T_ERR_INVALID_INDEX;
int IMPL_T_ERR_INVALID_ITEM = MPI_T_ERR_INVALID_ITEM;
int IMPL_T_ERR_INVALID_SESSION = MPI_T_ERR_INVALID_SESSION;
int IMPL_T_ERR_INVALID_HANDLE = MPI_T_ERR_INVALID_HANDLE;
int IMPL_T_ERR_INVALID_NAME = MPI_T_ERR_INVALID_NAME;
int IMPL_T_ERR_OUT_OF_HANDLES = MPI_T_ERR_OUT_OF_HANDLES;
int IMPL_T_ERR_OUT_OF_SESSIONS = MPI_T_ERR_OUT_OF_SESSIONS;
int IMPL_T_ERR_CVAR_SET_NOT_NOW = MPI_T_ERR_CVAR_SET_NOT_NOW;
int IMPL_T_ERR_CVAR_SET_NEVER = MPI_T_ERR_CVAR_SET_NEVER;
int IMPL_T_ERR_PVAR_NO_WRITE = MPI_T_ERR_PVAR_NO_WRITE;
int IMPL_T_ERR_PVAR_NO_STARTSTOP = MPI_T_ERR_PVAR_NO_STARTSTOP;
int IMPL_T_ERR_PVAR_NO_ATOMIC = MPI_T_ERR_PVAR_NO_ATOMIC;
int IMPL_ERR_LASTCODE = MPI_ERR_LASTCODE;

// Buffer Address Constants
void * IMPL_BOTTOM = MPI_BOTTOM;
void * IMPL_IN_PLACE = MPI_IN_PLACE;

// Assorted Constants
int IMPL_PROC_NULL = MPI_PROC_NULL;
int IMPL_ANY_SOURCE = MPI_ANY_SOURCE;
int IMPL_ANY_TAG = MPI_ANY_TAG;
int IMPL_UNDEFINED = MPI_UNDEFINED;
int IMPL_BSEND_OVERHEAD = MPI_BSEND_OVERHEAD;
int IMPL_KEYVAL_INVALID = MPI_KEYVAL_INVALID;
int IMPL_LOCK_EXCLUSIVE = MPI_LOCK_EXCLUSIVE;
int IMPL_LOCK_SHARED = MPI_LOCK_SHARED;
int IMPL_ROOT = MPI_ROOT;

// No Process Message Handle
MPI_Message IMPL_MESSAGE_NO_PROC = MPI_MESSAGE_NO_PROC;

#if 0
//Fortran status array size and reserved index values (C only)
int IMPL_F_STATUS_SIZE = MPI_F_STATUS_SIZE;
int IMPL_F_SOURCE      = MPI_F_SOURCE;
int IMPL_F_TAG         = MPI_F_TAG;
int IMPL_F_ERROR       = MPI_F_ERROR;
MPI_ADDRESS_KIND
MPI_COUNT_KIND
MPI_INTEGER_KIND
MPI_OFFSET_KIND
#endif

// Error-handling specifiers
MPI_Errhandler IMPL_ERRORS_ARE_FATAL = MPI_ERRORS_ARE_FATAL;
#if MPI_VERSION >= 4
MPI_Errhandler IMPL_ERRORS_ABORT     = MPI_ERRORS_ABORT;
#endif
MPI_Errhandler IMPL_ERRORS_RETURN    = MPI_ERRORS_RETURN;

// Named Predefined Datatypes
MPI_Datatype IMPL_CHAR = MPI_CHAR;
MPI_Datatype IMPL_SHORT = MPI_SHORT;
MPI_Datatype IMPL_INT = MPI_INT;
MPI_Datatype IMPL_LONG = MPI_LONG;
MPI_Datatype IMPL_LONG_LONG_INT = MPI_LONG_LONG_INT;
MPI_Datatype IMPL_LONG_LONG = MPI_LONG_LONG;
MPI_Datatype IMPL_SIGNED_CHAR = MPI_SIGNED_CHAR;
MPI_Datatype IMPL_UNSIGNED_CHAR = MPI_UNSIGNED_CHAR;
MPI_Datatype IMPL_UNSIGNED_SHORT = MPI_UNSIGNED_SHORT;
MPI_Datatype IMPL_UNSIGNED = MPI_UNSIGNED;
MPI_Datatype IMPL_UNSIGNED_LONG = MPI_UNSIGNED_LONG;
MPI_Datatype IMPL_UNSIGNED_LONG_LONG = MPI_UNSIGNED_LONG_LONG;
MPI_Datatype IMPL_FLOAT = MPI_FLOAT;
MPI_Datatype IMPL_DOUBLE = MPI_DOUBLE;
MPI_Datatype IMPL_LONG_DOUBLE = MPI_LONG_DOUBLE;
MPI_Datatype IMPL_WCHAR = MPI_WCHAR;
MPI_Datatype IMPL_C_BOOL = MPI_C_BOOL;

MPI_INT8_T
MPI_INT16_T
MPI_INT32_T
MPI_INT64_T
MPI_UINT8_T
MPI_UINT16_T
MPI_UINT32_T
MPI_UINT64_T
MPI_AINT
MPI_COUNT
MPI_OFFSET
MPI_C_COMPLEX
MPI_C_FLOAT_COMPLEX
MPI_C_DOUBLE_COMPLEX
MPI_C_LONG_DOUBLE_COMPLEX

MPI_Datatype IMPL_BYTE = MPI_BYTE;
MPI_Datatype IMPL_PACKED = MPI_PACKED;

MPI_INTEGER
MPI_REAL
MPI_DOUBLE_PRECISION
MPI_COMPLEX
MPI_LOGICAL
MPI_CHARACTER

MPI_CXX_BOOL
MPI_CXX_FLOAT_COMPLEX
MPI_CXX_DOUBLE_COMPLEX
MPI_CXX_LONG_DOUBLE_COMPLEX

MPI_DOUBLE_COMPLEX
MPI_INTEGER1
MPI_INTEGER2
MPI_INTEGER4
MPI_INTEGER8
MPI_INTEGER16
MPI_REAL2
MPI_REAL4
MPI_REAL8
MPI_REAL16
MPI_COMPLEX4
MPI_COMPLEX8
MPI_COMPLEX16
MPI_COMPLEX32

MPI_Datatype IMPL_FLOAT_INT = MPI_FLOAT_INT;
MPI_Datatype IMPL_DOUBLE_INT = MPI_DOUBLE_INT;
MPI_Datatype IMPL_LONG_INT = MPI_LONG_INT;
MPI_Datatype IMPL_2INT = MPI_2INT;
MPI_Datatype IMPL_SHORT_INT = MPI_SHORT_INT;
MPI_Datatype IMPL_LONG_DOUBLE_INT = MPI_LONG_DOUBLE_INT;

MPI_2REAL
MPI_2DOUBLE_PRECISION
MPI_2INTEGER

// Reserved communicators
MPI_Comm IMPL_COMM_WORLD = MPI_COMM_WORLD;
MPI_Comm IMPL_COMM_SELF  = MPI_COMM_SELF;

// Communicator split type constants
MPI_COMM_TYPE_SHARED
MPI_COMM_TYPE_HW_UNGUIDED
MPI_COMM_TYPE_HW_GUIDED

// Results of communicator and group comparisons
MPI_IDENT
MPI_CONGRUENT
MPI_SIMILAR MPI_UNEQUAL

// Environmental inquiry info key
MPI_Info MPI_INFO_ENV

// Environmental inquiry keys
MPI_TAG_UB
MPI_IO
MPI_HOST MPI_WTIME_IS_GLOBAL

// Collective Operations
MPI_Op IMPL_MAX = MPI_MAX;
MPI_Op IMPL_MIN = MPI_MIN;
MPI_Op IMPL_SUM = MPI_SUM;
MPI_Op IMPL_PROD = MPI_PROD;
MPI_Op IMPL_LAND = MPI_LAND;
MPI_Op IMPL_BAND = MPI_BAND;
MPI_Op IMPL_LOR = MPI_LOR;
MPI_Op IMPL_BOR = MPI_BOR;
MPI_Op IMPL_LXOR = MPI_LXOR;
MPI_Op IMPL_BXOR = MPI_BXOR;
MPI_Op IMPL_MAXLOC = MPI_MAXLOC;
MPI_Op IMPL_MINLOC = MPI_MINLOC;
MPI_Op IMPL_REPLACE = MPI_REPLACE;
MPI_Op IMPL_NO_OP = MPI_NO_OP;

// Null Handles
MPI_Group IMPL_GROUP_NULL  = MPI_GROUP_NULL;
MPI_Comm IMPL_COMM_NULL  = MPI_COMM_NULL;
MPI_Datatype IMPL_DATATYPE_NULL = MPI_DATATYPE_NULL;
MPI_Request IMPL_REQUEST_NULL = MPI_REQUEST_NULL;
MPI_Op IMPL_OP_NULL = MPI_OP_NULL;
MPI_Errhandler IMPL_ERRHANDLER_NULL = MPI_ERRHANDLER_NULL;
MPI_File IMPL_FILE_NULL = MPI_FILE_NULL;
MPI_Info IMPL_INFO_NULL = MPI_INFO_NULL;
#if MPI_VERSION >= 4
MPI_Session IMPL_SESSION_NULL = MPI_SESSION_NULL;
#endif
MPI_Win IMPL_WIN_NULL =  MPI_WIN_NULL;
MPI_Message IMPL_MESSAGE_NULL = MPI_MESSAGE_NULL;

// Empty group
MPI_Group IMPL_GROUP_EMPTY = MPI_GROUP_EMPTY;

// Topologies
MPI_GRAPH
MPI_CART
MPI_DIST_GRAPH

// Predefined functions
// TODO
// Deprecated predefined functions
// TODO

// Predefined Attribute Keys
MPI_APPNUM
MPI_LASTUSEDCODE
MPI_UNIVERSE_SIZE
MPI_WIN_BASE
MPI_WIN_DISP_UNIT
MPI_WIN_SIZE
MPI_WIN_CREATE_FLAVOR
MPI_WIN_MODEL

// MPI Window Create Flavors
MPI_WIN_FLAVOR_CREATE
MPI_WIN_FLAVOR_ALLOCATE
MPI_WIN_FLAVOR_DYNAMIC
MPI_WIN_FLAVOR_SHARED

// MPI Window Models
MPI_WIN_SEPARATE
MPI_WIN_UNIFIED
            
// Mode Constants
MPI_MODE_APPEND
MPI_MODE_CREATE
MPI_MODE_DELETE_ON_CLOSE
MPI_MODE_EXCL
MPI_MODE_NOCHECK
MPI_MODE_NOPRECEDE
MPI_MODE_NOPUT
MPI_MODE_NOSTORE
MPI_MODE_NOSUCCEED
MPI_MODE_RDONLY
MPI_MODE_RDWR
MPI_MODE_SEQUENTIAL
MPI_MODE_UNIQUE_OPEN
MPI_MODE_WRONLY

// Datatype Decoding Constants
MPI_COMBINER_CONTIGUOUS
MPI_COMBINER_DARRAY
MPI_COMBINER_DUP
MPI_COMBINER_F90_COMPLEX
MPI_COMBINER_F90_INTEGER
MPI_COMBINER_F90_REAL
MPI_COMBINER_HINDEXED
MPI_COMBINER_HVECTOR
MPI_COMBINER_INDEXED_BLOCK
MPI_COMBINER_HINDEXED_BLOCK
MPI_COMBINER_INDEXED
MPI_COMBINER_NAMED
MPI_COMBINER_RESIZED
MPI_COMBINER_STRUCT
MPI_COMBINER_SUBARRAY
MPI_COMBINER_VECTOR

// Threads Constants
MPI_THREAD_FUNNELED
MPI_THREAD_MULTIPLE
MPI_THREAD_SERIALIZED
MPI_THREAD_SINGLE

// File Operation Constants, Part 1
MPI_DISPLACEMENT_CURRENT

// File Operation Constants, Part 2
MPI_DISTRIBUTE_BLOCK
MPI_DISTRIBUTE_CYCLIC
MPI_DISTRIBUTE_DFLT_DARG
MPI_DISTRIBUTE_NONE
MPI_ORDER_C
MPI_ORDER_FORTRAN
MPI_SEEK_CUR
MPI_SEEK_END
MPI_SEEK_SET

// F90 Datatype Matching Constants
MPI_TYPECLASS_COMPLEX
MPI_TYPECLASS_INTEGER
MPI_TYPECLASS_REAL

// Constants Specifying Empty or Ignored Input
char *** IMPL_ARGVS_NULL = MPI_ARGVS_NULL;
char ** IMPL_ARGV_NULL = MPI_ARGV_NULL;
int * IMPL_ERRCODES_IGNORE = MPI_ERRCODES_IGNORE;
MPI_Status * IMPL_STATUSES_IGNORE = MPI_STATUSES_IGNORE;
MPI_Status * IMPL_STATUS_IGNORE = MPI_STATUS_IGNORE;
int * IMPL_UNWEIGHTED = MPI_UNWEIGHTED;
int * IMPL_WEIGHTS_EMPTY = MPI_WEIGHTS_EMPTY;
