#ifndef IMPL_PREDEFINED_H
#define IMPL_PREDEFINED_H

// error codes
int IMPL_ERR_BUFFER;
int IMPL_ERR_COUNT;
int IMPL_ERR_TYPE;
int IMPL_ERR_TAG;
int IMPL_ERR_COMM;
int IMPL_ERR_RANK;
int IMPL_ERR_REQUEST;
int IMPL_ERR_ROOT;
int IMPL_ERR_GROUP;
int IMPL_ERR_OP;
int IMPL_ERR_TOPOLOGY;
int IMPL_ERR_DIMS;
int IMPL_ERR_ARG;
int IMPL_ERR_UNKNOWN;
int IMPL_ERR_TRUNCATE;
int IMPL_ERR_OTHER;
int IMPL_ERR_INTERN;
int IMPL_ERR_PENDING;
int IMPL_ERR_IN_STATUS;
int IMPL_ERR_ACCESS;
int IMPL_ERR_AMODE;
int IMPL_ERR_ASSERT;
int IMPL_ERR_BAD_FILE;
int IMPL_ERR_BASE;
int IMPL_ERR_CONVERSION;
int IMPL_ERR_DISP;
int IMPL_ERR_DUP_DATAREP;
int IMPL_ERR_FILE_EXISTS;
int IMPL_ERR_FILE_IN_USE;
int IMPL_ERR_FILE;
int IMPL_ERR_INFO_KEY;
int IMPL_ERR_INFO_NOKEY;
int IMPL_ERR_INFO_VALUE;
int IMPL_ERR_INFO;
int IMPL_ERR_IO;
int IMPL_ERR_KEYVAL;
int IMPL_ERR_LOCKTYPE;
int IMPL_ERR_NAME;
int IMPL_ERR_NO_MEM;
int IMPL_ERR_NOT_SAME;
int IMPL_ERR_NO_SPACE;
int IMPL_ERR_NO_SUCH_FILE;
int IMPL_ERR_PORT;
int IMPL_ERR_PROC_ABORTED;
int IMPL_ERR_QUOTA;
int IMPL_ERR_READ_ONLY;
int IMPL_ERR_RMA_ATTACH;
int IMPL_ERR_RMA_CONFLICT;
int IMPL_ERR_RMA_RANGE;
int IMPL_ERR_RMA_SHARED;
int IMPL_ERR_RMA_SYNC;
int IMPL_ERR_RMA_FLAVOR;
int IMPL_ERR_SERVICE;
int IMPL_ERR_SESSION;
int IMPL_ERR_SIZE;
int IMPL_ERR_SPAWN;
int IMPL_ERR_UNSUPPORTED_DATAREP;
int IMPL_ERR_UNSUPPORTED_OPERATION;
int IMPL_ERR_VALUE_TOO_LARGE;
int IMPL_ERR_WIN;
int IMPL_T_ERR_CANNOT_INIT;
int IMPL_T_ERR_NOT_ACCESSIBLE;
int IMPL_T_ERR_NOT_INITIALIZED;
int IMPL_T_ERR_NOT_SUPPORTED;
int IMPL_T_ERR_MEMORY;
int IMPL_T_ERR_INVALID;
int IMPL_T_ERR_INVALID_INDEX;
int IMPL_T_ERR_INVALID_ITEM;
int IMPL_T_ERR_INVALID_SESSION;
int IMPL_T_ERR_INVALID_HANDLE;
int IMPL_T_ERR_INVALID_NAME;
int IMPL_T_ERR_OUT_OF_HANDLES;
int IMPL_T_ERR_OUT_OF_SESSIONS;
int IMPL_T_ERR_CVAR_SET_NOT_NOW;
int IMPL_T_ERR_CVAR_SET_NEVER;
int IMPL_T_ERR_PVAR_NO_WRITE;
int IMPL_T_ERR_PVAR_NO_STARTSTOP;
int IMPL_T_ERR_PVAR_NO_ATOMIC;
int IMPL_ERR_LASTCODE;

// Buffer Address Constants

// Assorted Constants
    // these should be different and never valid ranks
int IMPL_PROC_NULL;
int IMPL_ANY_SOURCE;
int IMPL_ROOT;
int IMPL_ANY_TAG;
int IMPL_UNDEFINED;
int IMPL_BSEND_OVERHEAD;
int IMPL_KEYVAL_INVALID;
int IMPL_LOCK_EXCLUSIVE;
int IMPL_LOCK_SHARED;

//Fortran status array size and reserved index values (C only)
int IMPL_F_STATUS_SIZE;
int IMPL_F_SOURCE;
int IMPL_F_TAG;
int IMPL_F_ERROR;
int IMPL_ADDRESS_KIND;
int IMPL_COUNT_KIND;
int IMPL_INTEGER_KIND;
int IMPL_OFFSET_KIND;

// Communicator split type constants
int IMPL_COMM_TYPE_SHARED;
int IMPL_COMM_TYPE_HW_UNGUIDED;
int IMPL_COMM_TYPE_HW_GUIDED;

// Results of communicator and group comparisons
int IMPL_IDENT;
int IMPL_CONGRUENT;
int IMPL_SIMILAR;
int IMPL_UNEQUAL;

// Environmental inquiry keys
int IMPL_TAG_UB;
int IMPL_IO;
int IMPL_HOST;
int IMPL_WTIME_IS_GLOBAL;

// Topologies
int IMPL_GRAPH;
int IMPL_CART;
int IMPL_DIST_GRAPH;

// Predefined Attribute Keys
int IMPL_APPNUM;
int IMPL_LASTUSEDCODE;
int IMPL_UNIVERSE_SIZE;
int IMPL_WIN_BASE;
int IMPL_WIN_DISP_UNIT;
int IMPL_WIN_SIZE;
int IMPL_WIN_CREATE_FLAVOR;
int IMPL_WIN_MODEL;

// MPI Window Create Flavors
int IMPL_WIN_FLAVOR_CREATE;
int IMPL_WIN_FLAVOR_ALLOCATE;
int IMPL_WIN_FLAVOR_DYNAMIC;
int IMPL_WIN_FLAVOR_SHARED;

// MPI Window Models
int IMPL_WIN_SEPARATE;
int IMPL_WIN_UNIFIED;

// Mode Constants
int IMPL_MODE_APPEND;
int IMPL_MODE_CREATE;
int IMPL_MODE_DELETE_ON_CLOSE;
int IMPL_MODE_EXCL;
int IMPL_MODE_NOCHECK;
int IMPL_MODE_NOPRECEDE;
int IMPL_MODE_NOPUT;
int IMPL_MODE_NOSTORE;
int IMPL_MODE_NOSUCCEED;
int IMPL_MODE_RDONLY;
int IMPL_MODE_RDWR;
int IMPL_MODE_SEQUENTIAL;
int IMPL_MODE_UNIQUE_OPEN;
int IMPL_MODE_WRONLY;

// Datatype Decoding Constants
int IMPL_COMBINER_CONTIGUOUS;
int IMPL_COMBINER_DARRAY;
int IMPL_COMBINER_DUP;
int IMPL_COMBINER_F90_COMPLEX;
int IMPL_COMBINER_F90_INTEGER;
int IMPL_COMBINER_F90_REAL;
int IMPL_COMBINER_HINDEXED;
int IMPL_COMBINER_HVECTOR;
int IMPL_COMBINER_INDEXED_BLOCK;
int IMPL_COMBINER_HINDEXED_BLOCK;
int IMPL_COMBINER_INDEXED;
int IMPL_COMBINER_NAMED;
int IMPL_COMBINER_RESIZED;
int IMPL_COMBINER_STRUCT;
int IMPL_COMBINER_SUBARRAY;
int IMPL_COMBINER_VECTOR;

// Threads Constants
int IMPL_THREAD_FUNNELED;
int IMPL_THREAD_MULTIPLE;
int IMPL_THREAD_SERIALIZED;
int IMPL_THREAD_SINGLE;

// File Operation Constants Part 1
int IMPL_DISPLACEMENT_CURRENT;
// File Operation Constants Part 2
int IMPL_DISTRIBUTE_BLOCK;
int IMPL_DISTRIBUTE_CYCLIC;
int IMPL_DISTRIBUTE_DFLT_DARG;
int IMPL_DISTRIBUTE_NONE;
int IMPL_ORDER_C;
int IMPL_ORDER_FORTRAN;
int IMPL_SEEK_CUR;
int IMPL_SEEK_END;
int IMPL_SEEK_SET;

// F90 Datatype Matching Constants
int IMPL_TYPECLASS_COMPLEX;
int IMPL_TYPECLASS_INTEGER;
int IMPL_TYPECLASS_REAL;

#endif
