#ifndef MUK_MPI_PREDEFINED_H
#define MUK_MPI_PREDEFINED_H

#ifndef MUK_EXTERN
#error You must define MUK_EXTERN outside of this header!
#endif

#ifndef MUK_CONST
#error You must define MUK_CONST outside of this header!
#endif

// error codes
MUK_EXTERN int MPI_SUCCESS;
MUK_EXTERN int MPI_ERR_BUFFER;
MUK_EXTERN int MPI_ERR_COUNT;
MUK_EXTERN int MPI_ERR_TYPE;
MUK_EXTERN int MPI_ERR_TAG;
MUK_EXTERN int MPI_ERR_COMM;
MUK_EXTERN int MPI_ERR_RANK;
MUK_EXTERN int MPI_ERR_REQUEST;
MUK_EXTERN int MPI_ERR_ROOT;
MUK_EXTERN int MPI_ERR_GROUP;
MUK_EXTERN int MPI_ERR_OP;
MUK_EXTERN int MPI_ERR_TOPOLOGY;
MUK_EXTERN int MPI_ERR_DIMS;
MUK_EXTERN int MPI_ERR_ARG;
MUK_EXTERN int MPI_ERR_UNKNOWN;
MUK_EXTERN int MPI_ERR_TRUNCATE;
MUK_EXTERN int MPI_ERR_OTHER;
MUK_EXTERN int MPI_ERR_INTERN;
MUK_EXTERN int MPI_ERR_PENDING;
MUK_EXTERN int MPI_ERR_IN_STATUS;
MUK_EXTERN int MPI_ERR_ACCESS;
MUK_EXTERN int MPI_ERR_AMODE;
MUK_EXTERN int MPI_ERR_ASSERT;
MUK_EXTERN int MPI_ERR_BAD_FILE;
MUK_EXTERN int MPI_ERR_BASE;
MUK_EXTERN int MPI_ERR_CONVERSION;
MUK_EXTERN int MPI_ERR_DISP;
MUK_EXTERN int MPI_ERR_DUP_DATAREP;
MUK_EXTERN int MPI_ERR_FILE_EXISTS;
MUK_EXTERN int MPI_ERR_FILE_IN_USE;
MUK_EXTERN int MPI_ERR_FILE;
MUK_EXTERN int MPI_ERR_INFO_KEY;
MUK_EXTERN int MPI_ERR_INFO_NOKEY;
MUK_EXTERN int MPI_ERR_INFO_VALUE;
MUK_EXTERN int MPI_ERR_INFO;
MUK_EXTERN int MPI_ERR_IO;
MUK_EXTERN int MPI_ERR_KEYVAL;
MUK_EXTERN int MPI_ERR_LOCKTYPE;
MUK_EXTERN int MPI_ERR_NAME;
MUK_EXTERN int MPI_ERR_NO_MEM;
MUK_EXTERN int MPI_ERR_NOT_SAME;
MUK_EXTERN int MPI_ERR_NO_SPACE;
MUK_EXTERN int MPI_ERR_NO_SUCH_FILE;
MUK_EXTERN int MPI_ERR_PORT;
#if MPI_VERSION >= 4
MUK_EXTERN int MPI_ERR_PROC_ABORTED;
#endif
MUK_EXTERN int MPI_ERR_QUOTA;
MUK_EXTERN int MPI_ERR_READ_ONLY;
MUK_EXTERN int MPI_ERR_RMA_ATTACH;
MUK_EXTERN int MPI_ERR_RMA_CONFLICT;
MUK_EXTERN int MPI_ERR_RMA_RANGE;
MUK_EXTERN int MPI_ERR_RMA_SHARED;
MUK_EXTERN int MPI_ERR_RMA_SYNC;
MUK_EXTERN int MPI_ERR_RMA_FLAVOR;
MUK_EXTERN int MPI_ERR_SERVICE;
#if MPI_VERSION >= 4
MUK_EXTERN int MPI_ERR_SESSION;
#endif
MUK_EXTERN int MPI_ERR_SIZE;
MUK_EXTERN int MPI_ERR_SPAWN;
MUK_EXTERN int MPI_ERR_UNSUPPORTED_DATAREP;
MUK_EXTERN int MPI_ERR_UNSUPPORTED_OPERATION;
#if MPI_VERSION >= 4
MUK_EXTERN int MPI_ERR_VALUE_TOO_LARGE;
#endif
MUK_EXTERN int MPI_ERR_WIN;
MUK_EXTERN int MPI_T_ERR_CANNOT_INIT;
#if 0
MUK_EXTERN int MPI_T_ERR_NOT_ACCESSIBLE;
#endif
MUK_EXTERN int MPI_T_ERR_NOT_INITIALIZED;
#if MPI_VERSION >= 4
MUK_EXTERN int MPI_T_ERR_NOT_SUPPORTED;
#endif
MUK_EXTERN int MPI_T_ERR_MEMORY;
MUK_EXTERN int MPI_T_ERR_INVALID;
MUK_EXTERN int MPI_T_ERR_INVALID_INDEX;
MUK_EXTERN int MPI_T_ERR_INVALID_ITEM;
MUK_EXTERN int MPI_T_ERR_INVALID_SESSION;
MUK_EXTERN int MPI_T_ERR_INVALID_HANDLE;
MUK_EXTERN int MPI_T_ERR_INVALID_NAME;
MUK_EXTERN int MPI_T_ERR_OUT_OF_HANDLES;
MUK_EXTERN int MPI_T_ERR_OUT_OF_SESSIONS;
MUK_EXTERN int MPI_T_ERR_CVAR_SET_NOT_NOW;
MUK_EXTERN int MPI_T_ERR_CVAR_SET_NEVER;
MUK_EXTERN int MPI_T_ERR_PVAR_NO_WRITE;
MUK_EXTERN int MPI_T_ERR_PVAR_NO_STARTSTOP;
MUK_EXTERN int MPI_T_ERR_PVAR_NO_ATOMIC;
MUK_EXTERN int MPI_ERR_LASTCODE;

// Buffer Address Constants
MUK_EXTERN void * MPI_BOTTOM;
MUK_EXTERN void * MPI_IN_PLACE;

// Assorted Constants
MUK_EXTERN int MPI_PROC_NULL;
MUK_EXTERN int MPI_ANY_SOURCE;
MUK_EXTERN int MPI_ANY_TAG;
MUK_EXTERN int MPI_UNDEFINED;
MUK_EXTERN int MPI_BSEND_OVERHEAD;
MUK_EXTERN int MPI_KEYVAL_INVALID;
MUK_EXTERN int MPI_LOCK_EXCLUSIVE;
MUK_EXTERN int MPI_LOCK_SHARED;
MUK_EXTERN int MPI_ROOT;

// No Process Message Handle
MUK_EXTERN MPI_Message MPI_MESSAGE_NO_PROC;

#if 0
//Fortran status array size and reserved index values (C only)
MUK_EXTERN int MPI_F_STATUS_SIZE;
int MPI_F_SOURCE;
int MPI_F_TAG;
int MPI_F_ERROR;
MUK_EXTERN int MPI_ADDRESS_KIND;
MUK_EXTERN int MPI_COUNT_KIND;
MUK_EXTERN int MPI_INTEGER_KIND;
MUK_EXTERN int MPI_OFFSET_KIND;
#endif

// Error-handling specifiers
MUK_EXTERN MPI_Errhandler MPI_ERRORS_ARE_FATAL;
#if MPI_VERSION >= 4
MUK_EXTERN MPI_Errhandler MPI_ERRORS_ABORT;
#endif
MUK_EXTERN MPI_Errhandler MPI_ERRORS_RETURN;

// Named Predefined Datatypes
MUK_EXTERN MUK_CONST MPI_Datatype MPI_CHAR;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_SHORT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LONG;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LONG_LONG_INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LONG_LONG;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_SIGNED_CHAR;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UNSIGNED_CHAR;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UNSIGNED_SHORT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UNSIGNED;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UNSIGNED_LONG;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UNSIGNED_LONG_LONG;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_FLOAT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_DOUBLE;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LONG_DOUBLE;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_WCHAR;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_C_BOOL;

MUK_EXTERN MUK_CONST MPI_Datatype MPI_INT8_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INT16_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INT32_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INT64_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UINT8_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UINT16_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UINT32_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_UINT64_T;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_AINT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_COUNT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_OFFSET;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_C_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_C_FLOAT_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_C_DOUBLE_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_C_LONG_DOUBLE_COMPLEX;

MUK_EXTERN MUK_CONST MPI_Datatype MPI_BYTE;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_PACKED;

MUK_EXTERN MUK_CONST MPI_Datatype MPI_INTEGER;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_REAL;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_DOUBLE_PRECISION;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LOGICAL;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_CHARACTER;

MUK_EXTERN MUK_CONST MPI_Datatype MPI_CXX_BOOL;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_CXX_FLOAT_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_CXX_DOUBLE_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_CXX_LONG_DOUBLE_COMPLEX;

#if 0
MUK_EXTERN MUK_CONST MPI_Datatype MPI_DOUBLE_COMPLEX;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INTEGER1;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INTEGER2;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INTEGER4;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INTEGER8;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_INTEGER16;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_REAL2;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_REAL4;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_REAL8;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_REAL16;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_COMPLEX4;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_COMPLEX8;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_COMPLEX16;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_COMPLEX32;
#endif

MUK_EXTERN MUK_CONST MPI_Datatype MPI_FLOAT_INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_DOUBLE_INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LONG_INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_2INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_SHORT_INT;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_LONG_DOUBLE_INT;

MUK_EXTERN MUK_CONST MPI_Datatype MPI_2REAL;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_2DOUBLE_PRECISION;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_2INTEGER;

// Reserved communicators
MUK_EXTERN MUK_CONST MPI_Comm MPI_COMM_WORLD;
MUK_EXTERN MUK_CONST MPI_Comm MPI_COMM_SELF;

// Communicator split type constants
MUK_EXTERN int MPI_COMM_TYPE_SHARED;
#if MPI_VERSION >= 4
MUK_EXTERN int MPI_COMM_TYPE_HW_UNGUIDED;
MUK_EXTERN int MPI_COMM_TYPE_HW_GUIDED;
#endif

// Results of communicator and group comparisons
MUK_EXTERN int MPI_IDENT;
MUK_EXTERN int MPI_CONGRUENT;
MUK_EXTERN int MPI_SIMILAR;
MUK_EXTERN int MPI_UNEQUAL;

// Environmental inquiry info key
MUK_EXTERN MPI_Info MPI_INFO_ENV;

// Environmental inquiry keys
MUK_EXTERN int MPI_TAG_UB;
MUK_EXTERN int MPI_IO;
MUK_EXTERN int MPI_HOST;
MUK_EXTERN int MPI_WTIME_IS_GLOBAL;

// Collective Operations
MUK_EXTERN MUK_CONST MPI_Op MPI_MAX;
MUK_EXTERN MUK_CONST MPI_Op MPI_MIN;
MUK_EXTERN MUK_CONST MPI_Op MPI_SUM;
MUK_EXTERN MUK_CONST MPI_Op MPI_PROD;
MUK_EXTERN MUK_CONST MPI_Op MPI_LAND;
MUK_EXTERN MUK_CONST MPI_Op MPI_BAND;
MUK_EXTERN MUK_CONST MPI_Op MPI_LOR;
MUK_EXTERN MUK_CONST MPI_Op MPI_BOR;
MUK_EXTERN MUK_CONST MPI_Op MPI_LXOR;
MUK_EXTERN MUK_CONST MPI_Op MPI_BXOR;
MUK_EXTERN MUK_CONST MPI_Op MPI_MAXLOC;
MUK_EXTERN MUK_CONST MPI_Op MPI_MINLOC;
MUK_EXTERN MUK_CONST MPI_Op MPI_REPLACE;
MUK_EXTERN MUK_CONST MPI_Op MPI_NO_OP;

// Null Handles
MUK_EXTERN MUK_CONST MPI_Group MPI_GROUP_NULL;
MUK_EXTERN MUK_CONST MPI_Comm MPI_COMM_NULL;
MUK_EXTERN MUK_CONST MPI_Datatype MPI_DATATYPE_NULL;
MUK_EXTERN MUK_CONST MPI_Request MPI_REQUEST_NULL;
MUK_EXTERN MUK_CONST MPI_Op MPI_OP_NULL;
MUK_EXTERN MUK_CONST MPI_Errhandler MPI_ERRHANDLER_NULL;
MUK_EXTERN MUK_CONST MPI_File MPI_FILE_NULL;
MUK_EXTERN MUK_CONST MPI_Info MPI_INFO_NULL;
#if MPI_VERSION >= 4
MUK_EXTERN MUK_CONST MPI_Session MPI_SESSION_NULL;
#endif
MUK_EXTERN MUK_CONST MPI_Win  MPI_WIN_NULL;
MUK_EXTERN MUK_CONST MPI_Message MPI_MESSAGE_NULL;

// Empty group
MUK_EXTERN MPI_Group MPI_GROUP_EMPTY;

// Topologies
MUK_EXTERN int MPI_GRAPH;
MUK_EXTERN int MPI_CART;
MUK_EXTERN int MPI_DIST_GRAPH;

// Predefined functions
// TODO
// Deprecated predefined functions
// TODO

// Predefined Attribute Keys
MUK_EXTERN int MPI_APPNUM;
MUK_EXTERN int MPI_LASTUSEDCODE;
MUK_EXTERN int MPI_UNIVERSE_SIZE;
MUK_EXTERN int MPI_WIN_BASE;
MUK_EXTERN int MPI_WIN_DISP_UNIT;
MUK_EXTERN int MPI_WIN_SIZE;
MUK_EXTERN int MPI_WIN_CREATE_FLAVOR;
MUK_EXTERN int MPI_WIN_MODEL;

// MPI Window Create Flavors
MUK_EXTERN int MPI_WIN_FLAVOR_CREATE;
MUK_EXTERN int MPI_WIN_FLAVOR_ALLOCATE;
MUK_EXTERN int MPI_WIN_FLAVOR_DYNAMIC;
MUK_EXTERN int MPI_WIN_FLAVOR_SHARED;

// MPI Window Models
MUK_EXTERN int MPI_WIN_SEPARATE;
MUK_EXTERN int MPI_WIN_UNIFIED;
            
// Mode Constants
MUK_EXTERN int MPI_MODE_APPEND;
MUK_EXTERN int MPI_MODE_CREATE;
MUK_EXTERN int MPI_MODE_DELETE_ON_CLOSE;
MUK_EXTERN int MPI_MODE_EXCL;
MUK_EXTERN int MPI_MODE_NOCHECK;
MUK_EXTERN int MPI_MODE_NOPRECEDE;
MUK_EXTERN int MPI_MODE_NOPUT;
MUK_EXTERN int MPI_MODE_NOSTORE;
MUK_EXTERN int MPI_MODE_NOSUCCEED;
MUK_EXTERN int MPI_MODE_RDONLY;
MUK_EXTERN int MPI_MODE_RDWR;
MUK_EXTERN int MPI_MODE_SEQUENTIAL;
MUK_EXTERN int MPI_MODE_UNIQUE_OPEN;
MUK_EXTERN int MPI_MODE_WRONLY;

// Datatype Decoding Constants
MUK_EXTERN int MPI_COMBINER_CONTIGUOUS;
MUK_EXTERN int MPI_COMBINER_DARRAY;
MUK_EXTERN int MPI_COMBINER_DUP;
MUK_EXTERN int MPI_COMBINER_F90_COMPLEX;
MUK_EXTERN int MPI_COMBINER_F90_INTEGER;
MUK_EXTERN int MPI_COMBINER_F90_REAL;
MUK_EXTERN int MPI_COMBINER_HINDEXED;
MUK_EXTERN int MPI_COMBINER_HVECTOR;
MUK_EXTERN int MPI_COMBINER_INDEXED_BLOCK;
MUK_EXTERN int MPI_COMBINER_HINDEXED_BLOCK;
MUK_EXTERN int MPI_COMBINER_INDEXED;
MUK_EXTERN int MPI_COMBINER_NAMED;
MUK_EXTERN int MPI_COMBINER_RESIZED;
MUK_EXTERN int MPI_COMBINER_STRUCT;
MUK_EXTERN int MPI_COMBINER_SUBARRAY;
MUK_EXTERN int MPI_COMBINER_VECTOR;

// Threads Constants
MUK_EXTERN int MPI_THREAD_FUNNELED;
MUK_EXTERN int MPI_THREAD_MULTIPLE;
MUK_EXTERN int MPI_THREAD_SERIALIZED;
MUK_EXTERN int MPI_THREAD_SINGLE;

// File Operation Constants, Part 1
MUK_EXTERN int MPI_DISPLACEMENT_CURRENT;

// File Operation Constants, Part 2
MUK_EXTERN int MPI_DISTRIBUTE_BLOCK;
MUK_EXTERN int MPI_DISTRIBUTE_CYCLIC;
MUK_EXTERN int MPI_DISTRIBUTE_DFLT_DARG;
MUK_EXTERN int MPI_DISTRIBUTE_NONE;
MUK_EXTERN int MPI_ORDER_C;
MUK_EXTERN int MPI_ORDER_FORTRAN;
MUK_EXTERN int MPI_SEEK_CUR;
MUK_EXTERN int MPI_SEEK_END;
MUK_EXTERN int MPI_SEEK_SET;

// F90 Datatype Matching Constants
MUK_EXTERN int MPI_TYPECLASS_COMPLEX;
MUK_EXTERN int MPI_TYPECLASS_INTEGER;
MUK_EXTERN int MPI_TYPECLASS_REAL;

// Constants Specifying Empty or Ignored Input
MUK_EXTERN char *** MPI_ARGVS_NULL;
MUK_EXTERN char ** MPI_ARGV_NULL;
MUK_EXTERN int * MPI_ERRCODES_IGNORE;
MUK_EXTERN MPI_Status * MPI_STATUSES_IGNORE;
MUK_EXTERN MPI_Status * MPI_STATUS_IGNORE;
#if 0 //ndef MPICH
MUK_EXTERN int * MPI_UNWEIGHTED;
MUK_EXTERN int * MPI_WEIGHTS_EMPTY;
#endif

#endif
