#ifndef MPICH_BUILTIN_HANDLES_H
#define MPICH_BUILTIN_HANDLES_H

MPICH_Comm MPICH_COMM_WORLD;
MPICH_Comm MPICH_COMM_SELF;

MPICH_Group MPICH_GROUP_EMPTY;

MPICH_Message MPICH_MESSAGE_NO_PROC;

MPICH_Op MPICH_MAX;
MPICH_Op MPICH_MIN;
MPICH_Op MPICH_SUM;
MPICH_Op MPICH_PROD;
MPICH_Op MPICH_LAND;
MPICH_Op MPICH_BAND;
MPICH_Op MPICH_LOR;
MPICH_Op MPICH_BOR;
MPICH_Op MPICH_LXOR;
MPICH_Op MPICH_BXOR;
MPICH_Op MPICH_MAXLOC;
MPICH_Op MPICH_MINLOC;
MPICH_Op MPICH_REPLACE;
MPICH_Op MPICH_NO_OP;

MPICH_Datatype MPICH_DATATYPE_NULL;
MPICH_Datatype MPICH_BYTE;
MPICH_Datatype MPICH_PACKED;
MPICH_Datatype MPICH_CHAR;
MPICH_Datatype MPICH_SHORT;
MPICH_Datatype MPICH_INT;
MPICH_Datatype MPICH_LONG;
MPICH_Datatype MPICH_FLOAT;
MPICH_Datatype MPICH_DOUBLE;
MPICH_Datatype MPICH_LONG_DOUBLE;
MPICH_Datatype MPICH_UNSIGNED_CHAR;
MPICH_Datatype MPICH_SIGNED_CHAR;
MPICH_Datatype MPICH_UNSIGNED_SHORT;
MPICH_Datatype MPICH_UNSIGNED_LONG;
MPICH_Datatype MPICH_UNSIGNED;
MPICH_Datatype MPICH_FLOAT_INT;
MPICH_Datatype MPICH_DOUBLE_INT;
MPICH_Datatype MPICH_LONG_DOUBLE_INT;
MPICH_Datatype MPICH_LONG_INT;
MPICH_Datatype MPICH_SHORT_INT;
MPICH_Datatype MPICH_2INT;
MPICH_Datatype MPICH_WCHAR;
MPICH_Datatype MPICH_LONG_LONG_INT;
MPICH_Datatype MPICH_LONG_LONG;
MPICH_Datatype MPICH_UNSIGNED_LONG_LONG;
MPICH_Datatype MPICH_2COMPLEX;
MPICH_Datatype MPICH_2DOUBLE_COMPLEX;

#endif
