#!/bin/bash

CC=gcc

MUKPATH=/home/jhammond/mukautuva

# rpath does not solve the problem of the impl-wrap.so location
# LD_LIBRARY_PATH is required
${CC} -I${MUKPATH} $@ -L${MUKPATH} -lmuk #-Wl,-rpath=${MUKPATH}
