#ifndef MUK_BUILTIN_HANDLES_H
#define MUK_BUILTIN_HANDLES_H

MUK_Request MUK_REQUEST_NULL;

MUK_Errhandler MUK_ERRHANDLER_NULL;

MUK_Info MUK_INFO_NULL;

MUK_Win MUK_WIN_NULL;

MUK_File MUK_FILE_NULL;

MUK_Comm MUK_COMM_NULL;
MUK_Comm MUK_COMM_WORLD;
MUK_Comm MUK_COMM_SELF;

MUK_Group MUK_GROUP_NULL;
MUK_Group MUK_GROUP_EMPTY;

MUK_Message MUK_MESSAGE_NULL;
MUK_Message MUK_MESSAGE_NO_PROC;

MUK_Op MUK_OP_NULL;
MUK_Op MUK_MAX;
MUK_Op MUK_MIN;
MUK_Op MUK_SUM;
MUK_Op MUK_PROD;
MUK_Op MUK_LAND;
MUK_Op MUK_BAND;
MUK_Op MUK_LOR;
MUK_Op MUK_BOR;
MUK_Op MUK_LXOR;
MUK_Op MUK_BXOR;
MUK_Op MUK_MAXLOC;
MUK_Op MUK_MINLOC;
MUK_Op MUK_REPLACE;
MUK_Op MUK_NO_OP;

MUK_Datatype MUK_DATATYPE_NULL;
MUK_Datatype MUK_BYTE;
MUK_Datatype MUK_PACKED;
MUK_Datatype MUK_CHAR;
MUK_Datatype MUK_SHORT;
MUK_Datatype MUK_INT;
MUK_Datatype MUK_LONG;
MUK_Datatype MUK_FLOAT;
MUK_Datatype MUK_DOUBLE;
MUK_Datatype MUK_LONG_DOUBLE;
MUK_Datatype MUK_UNSIGNED_CHAR;
MUK_Datatype MUK_SIGNED_CHAR;
MUK_Datatype MUK_UNSIGNED_SHORT;
MUK_Datatype MUK_UNSIGNED_LONG;
MUK_Datatype MUK_UNSIGNED;
MUK_Datatype MUK_FLOAT_INT;
MUK_Datatype MUK_DOUBLE_INT;
MUK_Datatype MUK_LONG_DOUBLE_INT;
MUK_Datatype MUK_LONG_INT;
MUK_Datatype MUK_SHORT_INT;
MUK_Datatype MUK_2INT;
MUK_Datatype MUK_WCHAR;
MUK_Datatype MUK_LONG_LONG_INT;
MUK_Datatype MUK_LONG_LONG;
MUK_Datatype MUK_UNSIGNED_LONG_LONG;
MUK_Datatype MUK_2COMPLEX;
MUK_Datatype MUK_2DOUBLE_COMPLEX;

#endif
