#undef NIMI_SUB

#if defined(USE_MPI_NAMESPACE)
#define NIMI_SUB(text) MPI ## _ ## text
#elif defined(USE_MUK_NAMESPACE)
#define NIMI_SUB(text) MUK ## _ ## text
#else
#error Namespace substitution problem
#endif

NIMI_SUB(Request) NIMI_SUB(REQUEST_NULL);

NIMI_SUB(Errhandler) NIMI_SUB(ERRHANDLER_NULL);

NIMI_SUB(Info) NIMI_SUB(INFO_NULL);

NIMI_SUB(Win) NIMI_SUB(WIN_NULL);

NIMI_SUB(File) NIMI_SUB(FILE_NULL);

NIMI_SUB(Comm) NIMI_SUB(COMM_NULL);
NIMI_SUB(Comm) NIMI_SUB(COMM_WORLD);
NIMI_SUB(Comm) NIMI_SUB(COMM_SELF);

NIMI_SUB(Group) NIMI_SUB(GROUP_NULL);
NIMI_SUB(Group) NIMI_SUB(GROUP_EMPTY);

NIMI_SUB(Message) NIMI_SUB(MESSAGE_NULL);
NIMI_SUB(Message) NIMI_SUB(MESSAGE_NO_PROC);

NIMI_SUB(Op) NIMI_SUB(OP_NULL);
NIMI_SUB(Op) NIMI_SUB(MAX);
NIMI_SUB(Op) NIMI_SUB(MIN);
NIMI_SUB(Op) NIMI_SUB(SUM);
NIMI_SUB(Op) NIMI_SUB(PROD);
NIMI_SUB(Op) NIMI_SUB(LAND);
NIMI_SUB(Op) NIMI_SUB(BAND);
NIMI_SUB(Op) NIMI_SUB(LOR);
NIMI_SUB(Op) NIMI_SUB(BOR);
NIMI_SUB(Op) NIMI_SUB(LXOR);
NIMI_SUB(Op) NIMI_SUB(BXOR);
NIMI_SUB(Op) NIMI_SUB(MAXLOC);
NIMI_SUB(Op) NIMI_SUB(MINLOC);
NIMI_SUB(Op) NIMI_SUB(REPLACE);
NIMI_SUB(Op) NIMI_SUB(NO_OP);

NIMI_SUB(Datatype) NIMI_SUB(DATATYPE_NULL);
NIMI_SUB(Datatype) NIMI_SUB(BYTE);
NIMI_SUB(Datatype) NIMI_SUB(PACKED);
NIMI_SUB(Datatype) NIMI_SUB(CHAR);
NIMI_SUB(Datatype) NIMI_SUB(SHORT);
NIMI_SUB(Datatype) NIMI_SUB(INT);
NIMI_SUB(Datatype) NIMI_SUB(LONG);
NIMI_SUB(Datatype) NIMI_SUB(FLOAT);
NIMI_SUB(Datatype) NIMI_SUB(DOUBLE);
NIMI_SUB(Datatype) NIMI_SUB(LONG_DOUBLE);
NIMI_SUB(Datatype) NIMI_SUB(UNSIGNED_CHAR);
NIMI_SUB(Datatype) NIMI_SUB(SIGNED_CHAR);
NIMI_SUB(Datatype) NIMI_SUB(UNSIGNED_SHORT);
NIMI_SUB(Datatype) NIMI_SUB(UNSIGNED_LONG);
NIMI_SUB(Datatype) NIMI_SUB(UNSIGNED);
NIMI_SUB(Datatype) NIMI_SUB(FLOAT_INT);
NIMI_SUB(Datatype) NIMI_SUB(DOUBLE_INT);
NIMI_SUB(Datatype) NIMI_SUB(LONG_DOUBLE_INT);
NIMI_SUB(Datatype) NIMI_SUB(LONG_INT);
NIMI_SUB(Datatype) NIMI_SUB(SHORT_INT);
NIMI_SUB(Datatype) NIMI_SUB(2INT);
NIMI_SUB(Datatype) NIMI_SUB(WCHAR);
NIMI_SUB(Datatype) NIMI_SUB(LONG_LONG_INT);
NIMI_SUB(Datatype) NIMI_SUB(LONG_LONG);
NIMI_SUB(Datatype) NIMI_SUB(UNSIGNED_LONG_LONG);
NIMI_SUB(Datatype) NIMI_SUB(2COMPLEX);
NIMI_SUB(Datatype) NIMI_SUB(2DOUBLE_COMPLEX);
