#ifndef OMPI_BUILTIN_HANDLES_H
#define OMPI_BUILTIN_HANDLES_H

OMPI_Request OMPI_REQUEST_NULL;

OMPI_Errhandler OMPI_ERRHANDLER_NULL;

OMPI_Info OMPI_INFO_NULL;

OMPI_Win OMPI_WIN_NULL;

OMPI_File OMPI_FILE_NULL;

OMPI_Comm OMPI_COMM_NULL;
OMPI_Comm OMPI_COMM_WORLD;
OMPI_Comm OMPI_COMM_SELF;

OMPI_Group OMPI_GROUP_NULL;
OMPI_Group OMPI_GROUP_EMPTY;

OMPI_Message OMPI_MESSAGE_NULL;
OMPI_Message OMPI_MESSAGE_NO_PROC;

OMPI_Op OMPI_OP_NULL;
OMPI_Op OMPI_MAX;
OMPI_Op OMPI_MIN;
OMPI_Op OMPI_SUM;
OMPI_Op OMPI_PROD;
OMPI_Op OMPI_LAND;
OMPI_Op OMPI_BAND;
OMPI_Op OMPI_LOR;
OMPI_Op OMPI_BOR;
OMPI_Op OMPI_LXOR;
OMPI_Op OMPI_BXOR;
OMPI_Op OMPI_MAXLOC;
OMPI_Op OMPI_MINLOC;
OMPI_Op OMPI_REPLACE;
OMPI_Op OMPI_NO_OP;

OMPI_Datatype OMPI_DATATYPE_NULL;
OMPI_Datatype OMPI_BYTE;
OMPI_Datatype OMPI_PACKED;
OMPI_Datatype OMPI_CHAR;
OMPI_Datatype OMPI_SHORT;
OMPI_Datatype OMPI_INT;
OMPI_Datatype OMPI_LONG;
OMPI_Datatype OMPI_FLOAT;
OMPI_Datatype OMPI_DOUBLE;
OMPI_Datatype OMPI_LONG_DOUBLE;
OMPI_Datatype OMPI_UNSIGNED_CHAR;
OMPI_Datatype OMPI_SIGNED_CHAR;
OMPI_Datatype OMPI_UNSIGNED_SHORT;
OMPI_Datatype OMPI_UNSIGNED_LONG;
OMPI_Datatype OMPI_UNSIGNED;
OMPI_Datatype OMPI_FLOAT_INT;
OMPI_Datatype OMPI_DOUBLE_INT;
OMPI_Datatype OMPI_LONG_DOUBLE_INT;
OMPI_Datatype OMPI_LONG_INT;
OMPI_Datatype OMPI_SHORT_INT;
OMPI_Datatype OMPI_2INT;
OMPI_Datatype OMPI_WCHAR;
OMPI_Datatype OMPI_LONG_LONG_INT;
OMPI_Datatype OMPI_LONG_LONG;
OMPI_Datatype OMPI_UNSIGNED_LONG_LONG;
OMPI_Datatype OMPI_2COMPLEX;
OMPI_Datatype OMPI_2DOUBLE_COMPLEX;

#endif
